trigger: none  # This pipeline triggers after CI completes

pool:
  vmImage: 'windows-latest'

resources:
  pipelines:
  - pipeline: CI  # Reference to the CI pipeline
    source: my-python-app
    trigger:
      branches:
        - main

stages:
- stage: Deploy
  dependsOn: []  # No dependencies, it runs when triggered
  condition: succeeded()
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy to Azure App Service
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download CI Build Artifacts'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProject)'
              pipeline: 'my-python-app-CI'  # Ensure it matches the CI pipeline name
              artifactName: 'drop'
              downloadPath: '$(Build.ArtifactStagingDirectory)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: 'AzureDevOps-ServiceConnection'
              appType: 'webApp'
              appName: 'flask-app-devops'
              package: '$(Build.ArtifactStagingDirectory)/drop'
