trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- script: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install requests
  displayName: 'Install dependencies'

- powershell: |
    # Start Flask app in the background
    $process = Start-Process -NoNewWindow -PassThru -FilePath "python" -ArgumentList "app.py"

    # Wait for Flask to start
    Start-Sleep -Seconds 5

    # Check if the Flask app is responding
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:5000" -UseBasicParsing
        Write-Host "Flask app started successfully"
    } catch {
        Write-Host "Flask app did not start in time"
        exit 1
    }

    # Stop the Flask app
    Stop-Process -Id $process.Id -Force
  displayName: 'Run Python App (Basic Check)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Publish Artifacts'
